dist: xenial
language: java
jdk: oraclejdk8

script:
  - ./gradlew build --scan -s

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $TEST_ROOT_FILE_PATH

branches:
  only:
    - master
